### ISSUE TITLE
Unable to start Callisto container;

### ISSUE THREAD

**Issue by alex270795** [wrike/callisto#12]
Hello,
I have tried to start callisto-chart in minicube, but I receive the following errors when callisto container is starting:
[Callisto logs.txt](https://github.com/user-attachments/files/16359762/Callisto.logs.txt)

Could you suggest how the issue can be solved?

BR,
Alex.

**Comment by vpokotilov** [comment]
@alex270795 hi, something is wrong with the yaml syntax
```
  in "/etc/callisto/browser-pod-manifest.yaml", line 17, column 7
could not find expected ':'
```

Try to check the syntax of this file, for example by checking the output of the `helm template .` command.

**Comment by alex270795** [comment]
Thanks a lot!
But now I receive another issue.
Have ever faced this issue? Callisto pod crashes .
[Callisto pod crashes.txt](https://github.com/user-attachments/files/16377577/Callisto.pod.crashes.txt)
![callisto](https://github.com/user-attachments/assets/73897930-33e8-47e0-97a6-9889bc4f33f5)

**Comment by vpokotilov** [comment]
@alex270795 Сan you get the callisto pod logs? There must be something useful there.

**Comment by alex270795** [comment]
@vpokotilov It's the same issue in "/etc/callisto/browser-pod-manifest.yaml", line 17, column 7
could not find expected ':' .
But, I don't understand where should be added ':' . 
I have copied this file from your repository:
![image](https://github.com/user-attachments/assets/a12b7139-8af7-4c5a-8cfd-c6f964c27d97)

Maybe you have changed something but don't commited to repository?

**Comment by vpokotilov** [comment]
@alex270795 You can view the contents of the rendered file using the `helm template .`command and try to find error there.  
Most likely the error occurs due to changes in values.yaml.

**Comment by alex270795** [comment]
@vpokotilov it's my helm template . check:
[helm template.txt](https://github.com/user-attachments/files/16378846/helm.template.txt)

**Comment by vpokotilov** [comment]
@alex270795 wrong indentation near resources:
```
      containers:
        - name: browser
          image: selenoid/vnc:chrome_80.0
          resources:
          {}
```

On the master branch it's different:
```
      containers:
        - name: browser
          image: selenoid/vnc:chrome_80.0
          resources:
            {}
```
